define(["require", "exports", "./LevelStats", "./Constants", "./Direction", "./DirectionChoices", "./DirectionToIndexLookup", "./Maze", "./PacMan", "./Tile", "./TileContent", "./Diags", "./ScorePanel", "./StatusPanel", "./GameStats", "./ScoreSprite", "./PowerPill", "./Pill", "./DotCounter", "./GhostHouseDoor", "./Fruit", "./FruitItem", "./GhostFrightSession", "./LevelProps", "./TimedSprite", "./TimedSpriteList", "./FruitSession", "./IntroCutScene", "./MainWindow", "./GameSoundPlayer"], function (require, exports, LevelStats_1, Constants_1, Direction_1, DirectionChoices_1, DirectionToIndexLookup_1, Maze_1, PacMan_1, Tile_1, TileContent_1, Diags_1, ScorePanel_1, StatusPanel_1, GameStats_1, ScoreSprite_1, PowerPill_1, Pill_1, DotCounter_1, GhostHouseDoor_1, Fruit_1, FruitItem_1, GhostFrightSession_1, LevelProps_1, TimedSprite_1, TimedSpriteList_1, FruitSession_1, IntroCutScene_1, MainWindow_1, GameSoundPlayer_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.GameSoundPlayer = exports.MainWindow = exports.IntroCutScene = exports.FruitSession = exports.TimedSpriteList = exports.TimedSprite = exports.LevelProps = exports.GhostFrightSession = exports.FruitItem = exports.Fruit = exports.GhostHouseDoor = exports.DotCounter = exports.Pill = exports.PowerPill = exports.ScoreSprite = exports.GameStats = exports.StatusPanel = exports.ScorePanel = exports.Diags = exports.TileContent = exports.Tile = exports.PacMan = exports.MazeBounds = exports.Maze = exports.DirectionToIndexLookup = exports.DirectionChoices = exports.Direction = exports.Constants = exports.LevelStats = void 0;
    Object.defineProperty(exports, "LevelStats", { enumerable: true, get: function () { return LevelStats_1.LevelStats; } });
    Object.defineProperty(exports, "Constants", { enumerable: true, get: function () { return Constants_1.Constants; } });
    Object.defineProperty(exports, "Direction", { enumerable: true, get: function () { return Direction_1.Direction; } });
    Object.defineProperty(exports, "DirectionChoices", { enumerable: true, get: function () { return DirectionChoices_1.DirectionChoices; } });
    Object.defineProperty(exports, "DirectionToIndexLookup", { enumerable: true, get: function () { return DirectionToIndexLookup_1.DirectionToIndexLookup; } });
    Object.defineProperty(exports, "Maze", { enumerable: true, get: function () { return Maze_1.Maze; } });
    Object.defineProperty(exports, "MazeBounds", { enumerable: true, get: function () { return Maze_1.MazeBounds; } });
    Object.defineProperty(exports, "PacMan", { enumerable: true, get: function () { return PacMan_1.PacMan; } });
    Object.defineProperty(exports, "Tile", { enumerable: true, get: function () { return Tile_1.Tile; } });
    Object.defineProperty(exports, "TileContent", { enumerable: true, get: function () { return TileContent_1.TileContent; } });
    Object.defineProperty(exports, "Diags", { enumerable: true, get: function () { return Diags_1.Diags; } });
    Object.defineProperty(exports, "ScorePanel", { enumerable: true, get: function () { return ScorePanel_1.ScorePanel; } });
    Object.defineProperty(exports, "StatusPanel", { enumerable: true, get: function () { return StatusPanel_1.StatusPanel; } });
    Object.defineProperty(exports, "GameStats", { enumerable: true, get: function () { return GameStats_1.GameStats; } });
    Object.defineProperty(exports, "ScoreSprite", { enumerable: true, get: function () { return ScoreSprite_1.ScoreSprite; } });
    Object.defineProperty(exports, "PowerPill", { enumerable: true, get: function () { return PowerPill_1.PowerPill; } });
    Object.defineProperty(exports, "Pill", { enumerable: true, get: function () { return Pill_1.Pill; } });
    Object.defineProperty(exports, "DotCounter", { enumerable: true, get: function () { return DotCounter_1.DotCounter; } });
    Object.defineProperty(exports, "GhostHouseDoor", { enumerable: true, get: function () { return GhostHouseDoor_1.GhostHouseDoor; } });
    Object.defineProperty(exports, "Fruit", { enumerable: true, get: function () { return Fruit_1.Fruit; } });
    Object.defineProperty(exports, "FruitItem", { enumerable: true, get: function () { return FruitItem_1.FruitItem; } });
    Object.defineProperty(exports, "GhostFrightSession", { enumerable: true, get: function () { return GhostFrightSession_1.GhostFrightSession; } });
    Object.defineProperty(exports, "LevelProps", { enumerable: true, get: function () { return LevelProps_1.LevelProps; } });
    Object.defineProperty(exports, "TimedSprite", { enumerable: true, get: function () { return TimedSprite_1.TimedSprite; } });
    Object.defineProperty(exports, "TimedSpriteList", { enumerable: true, get: function () { return TimedSpriteList_1.TimedSpriteList; } });
    Object.defineProperty(exports, "FruitSession", { enumerable: true, get: function () { return FruitSession_1.FruitSession; } });
    Object.defineProperty(exports, "IntroCutScene", { enumerable: true, get: function () { return IntroCutScene_1.IntroCutScene; } });
    Object.defineProperty(exports, "MainWindow", { enumerable: true, get: function () { return MainWindow_1.MainWindow; } });
    Object.defineProperty(exports, "GameSoundPlayer", { enumerable: true, get: function () { return GameSoundPlayer_1.GameSoundPlayer; } });
});
//# sourceMappingURL=_exports.js.map